#Reference: https://www.mkdocs.org/user-guide/configuration/

site_name: OpenDI Roles and User Stories
repo_url: https://github.com/opendi-org/roles-user-stories  #This will be the public repo
edit_uri: blob/dev/docs                                     #URI Partial, added to repo URL to link to editable version of user's current page

docs_dir: "docs"  #Local directory for docs .md files

nav:
  - Overview:
    - 'OpenDI': 'OpenDI Intro Material.md'
    - 'Roles and User Stories': 'index.md'
  - Roles:
    - 'Decision Maker': 'Roles/Decision Maker.md'
    - 'DI Analyst': 'Roles/DI Analyst.md'
    - 'Decision Model Builder': 'Roles/Decision Model Builder.md'
    - 'Decision Asset Manager': 'Roles/Decision Asset Manager.md'
    - 'OpenDI System Administrator': 'Roles/OpenDI System Administrator.md'
    - 'Decision Simulation Builder': 'Roles/Decision Simulation Builder.md'
    - 'Decision Simulation Manager': 'Roles/Decision Simulation Manager.md'
    - 'Decision Monitor Builder': 'Roles/Decision Monitor Builder.md'
    - 'Decision Monitor': 'Roles/Decision Monitor.md'
    - 'Decision Quality Assurance Manager': 'Roles/Decision Quality Assurance Manager.md'
  - 'OpenDI Glossary': 'OpenDI Glossary.md'

# Exclude _Role Page Template.md
exclude_docs: |
  _*.md

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  navigation_depth: 5


# Material is a third-party theme
# https://squidfunk.github.io/mkdocs-material/
# theme:
#   name: material

#   features:
#     - navigation.tabs
#     - navigation.tabs.sticky
#     - toc.integrate
#     - toc.follow